---
http:
  routers:
    wud:
      rule: Host(`wud.${DOMAIN}`)
      service: wud 
      tls: {}
      middlewares:
        - authentik@file
  services:
    wud:
      loadBalancer:
        servers:
          - url: http://monitoring:3000