---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# ── Logging ──────────────────────────────────────────────────────────
log:
  level: ERROR
  filePath: /var/log/traefik/traefik.log
accessLog:
  filters:
    statusCodes:
      - 204-299
      - 400-499
      - 500-599
  filePath: /var/log/traefik/access.log

# ── API & Dashboard (will listen on :8080) ───────────────────────────
api:
  dashboard: true
#  insecure: true

# ── EntryPoints ───────────────────────────────────────────────────────
entryPoints:
  web:
    address: ${HTTP_PORT}
    forwardedHeaders:
      trustedIPs: &trustedIps
        - 71.233.101.73/32
        - 100.0.71.40/32
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    http:
      middlewares:
        - security-headers@file
        - rate-limit@file
        - crowdsec@file

  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs: *trustedIps
    http:
      middlewares:
        - security-headers@file
        - rate-limit@file
        - crowdsec@file
      tls:
        certResolver: myresolver
        domains:
          - main: ${DOMAIN}
  ssh:
    address: ${SSH_PORT}

serversTransport:
  insecureSkipVerify: true

experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2

# ── Providers ────────────────────────────────────────────────────────
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true

# ── Certificates (ACME) ──────────────────────────────────────────────
certificatesResolvers:
  myresolver:
    acme:
      email: ${CF_API_EMAIL}
      storage: /acme/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53