---
http:
  routers:
    navidrome:
      rule: Host(`musica.${DOMAIN}`)
      middlewares:
      - authentik@file
      priority: 10
    service: navidrome
    navidrome-auth:
      rule: "Host(`musica.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      service: authentik
    to-subsonic:
      entryPoints: websecure
      rule: "Host(`musica.${DOMAIN}`) && PathPrefix(`/rest/`)"
      service: navidrome
      priority: 150
  services:
    navidrome:
      loadBalancer:
        servers:
          - url: http://navidrome:4533